<?php
return array(
        /* base url*/
        'baseUrl' => 'http://' . Request::server('HTTP_HOST') . '/ilanji_crm_new/',
        'absPath'  => Request::server('HTTP_HOST') . '/ilanji_crm_new/',
        'basePublic' => 'http://' . Request::server('HTTP_HOST') . '/ilanji_crm_new/public/',
        'title'   => 'Island Maids',
        'branchlist' => array('1' => 'Ang Monkia','2' => 'Bedok','3' => 'HQ'),
        'nationality' => array('1' => 'INDONESIA','2' => 'MYANMAR','3' => 'PHILIPPINES','4' => 'CAMBODIA','5' => 'INDIA', '6' => 'SRI LANKA', '7' => 'OTHERS'),
        'countryWork' => array('1' => 'HONG KONG','2' => 'TAIWAN', '3' => 'SINGAPORE','4' => 'MALAYSIA','5' => 'MIDDLE EAST','6' => 'INDONESIA','7' => 'OTHERS'),
        //'resultStatus' => array('4' => 'In-Progress','1' => 'Success','2' => 'Failure','3' => 'Others','5' => 'Cold leads','6' => 'Warm leads','7' => 'Hot Leads','8' => 'Appointment','9' =>  'Lost Case','10' => 'Sealed'),
        'resultStatus' => array('4' => 'Assigned','1' => 'Success','2' => 'Late Selection','3' => 'Others','5' => 'Cold leads','6' => 'Warm leads','7' => 'Hot Leads','8' => 'Appointment','9' => 'Lost Case','10' => 'Sealed','11' => 'In-Progress'),
        'resultColor' => array('4' => '#1BF0C6','1' => '#5cb85c','2' => '#F98D52','3' => '#F3EF69','5' => '#E98BD5','6' => '#9564e2','7' => '#f34541','8' => '#3F8DD1','9' => '#000','10' => '#00acec','11' => '#666'),
        'reslabel' => array('4' => 'label-default','1' => 'label-success','3' => 'label-default','5' => 'label-default','6' => 'label-info','7' => 'label-contrast','8' => 'label-warning','9' => 'label-inverse','10' => 'label-primary'),
        'app_approve_status' => array('4' => 'Pending','1' => 'Approve','2' => 'Appeal','3' => 'Reject'),
        'lead_icon' => array('1' => 'icon-check','2' => 'icon-exclamation-sign','3' => 'icon-exclamation-sign','4' => 'icon-refresh','5' => 'icon-cloud','6' => 'icon-circle-blank','7' => 'icon-sun','8' => 'icon-credit-card','9' => ' icon-globe','10' => ' icon-shield','11' => 'icon-gears'),
        'contract_icon' => array('1' => 'icon-asterisk','2' => 'icon-exchange','3' => 'icon-compass','4' => 'icon-road','5' => 'icon-pushpin','6' => 'icon-certificate','7' => 'icon-ticket','8' => 'icon-qrcode'),
        'fee_approval' => array('0' => 'Pending','1' => 'Approved','2' => 'Rejected'),
        'approval' => array('1' => 'Approved','2' => 'Rejected'),
        'punch_out_mode'    => array('2' => 'User','3' => 'Auto'),
        'account_save_opt'    => array('1' => 'Approved','2' => 'For Approval','3' => 'Draft'),
        'com_cost_type'  => array('1' => 'Contract','2' => 'Bonus'),
        'range_type'    =>  array('1' => 'Within Range','Greater than'),
        'loan_status' => array('1' => 'Paid', '0' => 'Pending'),
        'holiday_type' => array('1' => 'Public Holiday','2' => 'Company Holiday'),
        'cal_type' => array('5' => '5 Days Week','6' => '6 Days Week'),
        'work_abs' => array('9' => 'O','7' => 'P'),
        'day_type' => array('1' => 'Working Day','0' => 'Not Working Day'),
        'month_txt' => array('1' => 'January','2' => 'February','3' => 'March','4' => 'April','5' => 'May','6' => 'June','7' => 'July','8' => 'August','9' => 'September','10' => 'October','11' => 'November', '12' => 'December'),
        'process_status' => array('1' => 'Contract','2' => 'Application','3' => 'Application approved','4' => 'Insurance','5' => 'Maid Arrival','6' => 'Handover','7' => 'E-issue','8'=> 'Document'),
        /* Lead mode */
        'leadMode' => array('1' => 'Direct','2' => 'Indirect'),
        'gender'   => array('1' => 'Male','2' => 'Female'),
        'systemUser' => array('1' => 'Super User','2' => 'Branch Manager','3' => 'Sales Consultant'),
        'payMode' => array('1' => 'Cash','2' => 'Cheque'),
        'feeType' => array('1' => 'Admin Fee','2' => 'Insurance Fee','3' => 'Agency Fee','4' => 'Loan'),
        'MartialStatus' => array('1' => 'Single','2' => 'Married','3' => 'Widow'),
        'availStatus' => array('0' => 'Available','1' => 'Contract In-Progress','2' => 'Contracted','3' => 'Block','4' => 'Taken','5' => 'Canceled'),
        'tempPath'=> '/public/upload_files/temp/',
        'imagePath' =>  'public/images/',
        'tempPathUrl' => 'public/upload_files/temp/',
        'uploadPath' => 'public/upload_files/',
        'account_type' => array('1' => 'Income', '2' => 'Expense', '3' => 'Payment Account'),
        'coaGroup' => array('1' => 'Assets', '2' => 'Liabilities', '3' => 'Income', '4' => 'Expense'),
        'nric' => array('1' => 'NRIC Pink', '2' => 'NRIC Blue', '3' => 'FIN'),
        'reimburse_status' => array('0' => 'Pending', '1' => 'Draft', '2' => 'Submitted','3' => 'Approved','4' => 'Cheque Issued','5' => 'Rejected'),
        'admin_reimburse_status' => array('0' => 'Pending', '1' => 'Draft', '2' => 'Submitted','3' => 'Issue Cheque','4' => 'Cheque Issued','5' => 'Rejected'),
        'address_type' => array('1' => 'Residential', '2' => 'Office'),
        'nationality' => array(
                                    '193' => 'Afghan',
                                    '1' => 'Albanian',
                                    '2' => 'Algerian',
                                    '3' => 'American',
                                    '4' => 'Andorran',
                                    '5' => 'Angolan',
                                    '6' => 'Antiguans',
                                    '7' => 'Argentinean',
                                    '8' => 'Armenian',
                                    '9' => 'Australian',
                                    '10' => 'Austrian',
                                    '11' => 'Azerbaijani',
                                    '12' => 'Bahamian',
                                    '13' => 'Bahraini',
                                    '14' => 'Bangladeshi',
                                    '15' => 'Barbadian',
                                    '16' => 'Barbudans',
                                    '17' => 'Batswana',
                                    '18' => 'Belarusian',
                                    '19' => 'Belgian',
                                    '20' => 'Belizean',
                                    '21' => 'Beninese',
                                    '22' => 'Bhutanese',
                                    '23' => 'Bolivian',
                                    '24' => 'Bosnian',
                                    '25' => 'Brazilian',
                                    '26' => 'British',
                                    '27' => 'Bruneian',
                                    '28' => 'Bulgarian',
                                    '29' => 'Burkinabe',
                                    '30' => 'Burmese',
                                    '31' => 'Burundian',
                                    '32' => 'Cambodian',
                                    '33' => 'Cameroonian',
                                    '34' => 'Canadian',
                                    '35' => 'Cape Verdean',
                                    '36' => 'Central African',
                                    '37' => 'Chadian',
                                    '38' => 'Chilean',
                                    '39' => 'Chinese',
                                    '40' => 'Colombian',
                                    '41' => 'Comoran',
                                    '42' => 'Congolese',
                                    '43' => 'Costa Rican',
                                    '44' => 'Croatian',
                                    '45' => 'Cuban',
                                    '46' => 'Cypriot',
                                    '47' => 'Czech',
                                    '48' => 'Danish',
                                    '49' => 'Djibouti',
                                    '50' => 'Dominican',
                                    '51' => 'Dutch',
                                    '52' => 'East Timorese',
                                    '53' => 'Ecuadorean',
                                    '54' => 'Egyptian',
                                    '55' => 'Emirian',
                                    '56' => 'Equatorial Guinean',
                                    '57' => 'Eritrean',
                                    '58' => 'Estonian',
                                    '59' => 'Ethiopian',
                                    '60' => 'Fijian',
                                    '61' => 'Filipino',
                                    '62' => 'Finnish',
                                    '63' => 'French',
                                    '64' => 'Gabonese',
                                    '65' => 'Gambian',
                                    '66' => 'Georgian',
                                    '67' => 'German',
                                    '68' => 'Ghanaian',
                                    '69' => 'Greek',
                                    '70' => 'Grenadian',
                                    '71' => 'Guatemalan',
                                    '72' => 'Guinea-Bissauan',
                                    '73' => 'Guinean',
                                    '74' => 'Guyanese',
                                    '75' => 'Haitian',
                                    '76' => 'Herzegovinian',
                                    '77' => 'Honduran',
                                    '78' => 'Hungarian',
                                    '79' => 'I-Kiribati',
                                    '80' => 'Icelander',
                                    '81' => 'Indian',
                                    '82' => 'Indonesian',
                                    '83' => 'Iranian',
                                    '84' => 'Iraqi',
                                    '85' => 'Irish',
                                    '86' => 'Israeli',
                                    '87' => 'Italian',
                                    '88' => 'Ivorian',
                                    '89' => 'Jamaican',
                                    '90' => 'Japanese',
                                    '91' => 'Jordanian',
                                    '92' => 'Kazakhstani',
                                    '93' => 'Kenyan',
                                    '94' => 'Kittian and Nevisian',
                                    '95' => 'Kuwaiti',
                                    '96' => 'Kyrgyz',
                                    '97' => 'Laotian',
                                    '98' => 'Latvian',
                                    '99' => 'Lebanese',
                                    '100' => 'Liberian',
                                    '101' => 'Libyan',
                                    '102' => 'Liechtensteiner',
                                    '103' => 'Lithuanian',
                                    '104' => 'Luxembourger',
                                    '105' => 'Macedonian',
                                    '106' => 'Malagasy',
                                    '107' => 'Malawian',
                                    '108' => 'Malaysian',
                                    '109' => 'Maldivan',
                                    '110' => 'Malian',
                                    '111' => 'Maltese',
                                    '112' => 'Marshallese',
                                    '113' => 'Mauritanian',
                                    '114' => 'Mauritian',
                                    '115' => 'Mexican',
                                    '116' => 'Micronesian',
                                    '117' => 'Moldovan',
                                    '118' => 'Monacan',
                                    '119' => 'Mongolian',
                                    '120' => 'Moroccan',
                                    '121' => 'Mosotho',
                                    '122' => 'Motswana',
                                    '123' => 'Mozambican',
                                    '124' => 'Namibian',
                                    '125' => 'Nauruan',
                                    '126' => 'Nepalese',
                                    '127' => 'NewZealander',
                                    '128' => 'Nicaraguan',
                                    '129' => 'Nigerian',
                                    '130' => 'Nigerien',
                                    '131' => 'North Korean',
                                    '132' => 'Northern Irish',
                                    '133' => 'Norwegian',
                                    '134' => 'Omani',
                                    '135' => 'Pakistani',
                                    '136' => 'Palauan',
                                    '137' => 'Panamanian',
                                    '138' => 'Papua New Guinean',
                                    '139' => 'Paraguayan',
                                    '140' => 'Peruvian',
                                    '141' => 'Polish',
                                    '142' => 'Portuguese',
                                    '143' => 'Qatari',
                                    '144' => 'Romanian',
                                    '145' => 'Russian',
                                    '146' => 'Rwandan',
                                    '147' => 'Saint Lucian',
                                    '148' => 'Salvadoran',
                                    '149' => 'Samoan',
                                    '150' => 'San Marinese',
                                    '151' => 'Sao Tomean',
                                    '152' => 'Saudi',
                                    '153' => 'Scottish',
                                    '154' => 'Senegalese',
                                    '155' => 'Serbian',
                                    '156' => 'Seychellois',
                                    '157' => 'Sierra Leonean',
                                    '158' => 'Singaporean',
                                    '159' => 'Slovakian',
                                    '160' => 'Slovenian',
                                    '161' => 'Solomon Islander',
                                    '162' => 'Somali',
                                    '163' => 'South African',
                                    '164' => 'South Korean',
                                    '165' => 'Spanish',
                                    '166' => 'Sri Lankan',
                                    '167' => 'Sudanese',
                                    '168' => 'Surinamer',
                                    '169' => 'Swazi',
                                    '170' => 'Swedish',
                                    '171' => 'Swiss',
                                    '172' => 'Syrian',
                                    '173' => 'Taiwanese',
                                    '174' => 'Tajik',
                                    '175' => 'Tanzanian',
                                    '176' => 'Thai',
                                    '177' => 'Togolese',
                                    '178' => 'Tongan',
                                    '179' => 'Trinidadian/Tobagonian',
                                    '180' => 'Tunisian',
                                    '181' => 'Turkish',
                                    '182' => 'Tuvaluan',
                                    '183' => 'Ugandan',
                                    '184' => 'Ukrainian',
                                    '185' => 'Uruguayan',
                                    '186' => 'Uzbekistani',
                                    '187' => 'Venezuelan',
                                    '188' => 'Vietnamese',
                                    '189' => 'Welsh',
                                    '190' => 'Yemenite',
                                    '191' => 'Zambian',
                                    '192' => 'Zimbabwean'
                        ),
        'country' => array(
                                                                  "AF" => "Afghanistan",
                                                                  "AL" => "Albania",
                                                                  "DZ" => "Algeria",
                                                                  "AS" => "American Samoa",
                                                                  "AD" => "Andorra",
                                                                  "AO" => "Angola",
                                                                  "AI" => "Anguilla",
                                                                  "AQ" => "Antarctica",
                                                                  "AG" => "Antigua And Barbuda",
                                                                  "AR" => "Argentina",
                                                                  "AM" => "Armenia",
                                                                  "AW" => "Aruba",
                                                                  "AU" => "Australia",
                                                                  "AT" => "Austria",
                                                                  "AZ" => "Azerbaijan",
                                                                  "BS" => "Bahamas",
                                                                  "BH" => "Bahrain",
                                                                  "BD" => "Bangladesh",
                                                                  "BB" => "Barbados",
                                                                  "BY" => "Belarus",
                                                                  "BE" => "Belgium",
                                                                  "BZ" => "Belize",
                                                                  "BJ" => "Benin",
                                                                  "BM" => "Bermuda",
                                                                  "BT" => "Bhutan",
                                                                  "BO" => "Bolivia",
                                                                  "BA" => "Bosnia And Herzegowina",
                                                                  "BW" => "Botswana",
                                                                  "BV" => "Bouvet Island",
                                                                  "BR" => "Brazil",
                                                                  "IO" => "British Indian Ocean Territory",
                                                                  "BN" => "Brunei Darussalam",
                                                                  "BG" => "Bulgaria",
                                                                  "BF" => "Burkina Faso",
                                                                  "BI" => "Burundi",
                                                                  "KH" => "Cambodia",
                                                                  "CM" => "Cameroon",
                                                                  "CA" => "Canada",
                                                                  "CV" => "Cape Verde",
                                                                  "KY" => "Cayman Islands",
                                                                  "CF" => "Central African Republic",
                                                                  "TD" => "Chad",
                                                                  "CL" => "Chile",
                                                                  "CN" => "China",
                                                                  "CX" => "Christmas Island",
                                                                  "CC" => "Cocos (Keeling) Islands",
                                                                  "CO" => "Colombia",
                                                                  "KM" => "Comoros",
                                                                  "CG" => "Congo",
                                                                  "CD" => "Congo, The Democratic Republic Of The",
                                                                  "CK" => "Cook Islands",
                                                                  "CR" => "Costa Rica",
                                                                  "CI" => "Cote D'Ivoire",
                                                                  "HR" => "Croatia (Local Name: Hrvatska)",
                                                                  "CU" => "Cuba",
                                                                  "CY" => "Cyprus",
                                                                  "CZ" => "Czech Republic",
                                                                  "DK" => "Denmark",
                                                                  "DJ" => "Djibouti",
                                                                  "DM" => "Dominica",
                                                                  "DO" => "Dominican Republic",
                                                                  "TP" => "East Timor",
                                                                  "EC" => "Ecuador",
                                                                  "EG" => "Egypt",
                                                                  "SV" => "El Salvador",
                                                                  "GQ" => "Equatorial Guinea",
                                                                  "ER" => "Eritrea",
                                                                  "EE" => "Estonia",
                                                                  "ET" => "Ethiopia",
                                                                  "FK" => "Falkland Islands (Malvinas)",
                                                                  "FO" => "Faroe Islands",
                                                                  "FJ" => "Fiji",
                                                                  "FI" => "Finland",
                                                                  "FR" => "France",
                                                                  "FX" => "France, Metropolitan",
                                                                  "GF" => "French Guiana",
                                                                  "PF" => "French Polynesia",
                                                                  "TF" => "French Southern Territories",
                                                                  "GA" => "Gabon",
                                                                  "GM" => "Gambia",
                                                                  "GE" => "Georgia",
                                                                  "DE" => "Germany",
                                                                  "GH" => "Ghana",
                                                                  "GI" => "Gibraltar",
                                                                  "GR" => "Greece",
                                                                  "GL" => "Greenland",
                                                                  "GD" => "Grenada",
                                                                  "GP" => "Guadeloupe",
                                                                  "GU" => "Guam",
                                                                  "GT" => "Guatemala",
                                                                  "GN" => "Guinea",
                                                                  "GW" => "Guinea-Bissau",
                                                                  "GY" => "Guyana",
                                                                  "HT" => "Haiti",
                                                                  "HM" => "Heard And Mc Donald Islands",
                                                                  "VA" => "Holy See (Vatican City State)",
                                                                  "HN" => "Honduras",
                                                                  "HK" => "Hong Kong",
                                                                  "HU" => "Hungary",
                                                                  "IS" => "Iceland",
                                                                  "IN" => "India",
                                                                  "ID" => "Indonesia",
                                                                  "IR" => "Iran (Islamic Republic Of)",
                                                                  "IQ" => "Iraq",
                                                                  "IE" => "Ireland",
                                                                  "IL" => "Israel",
                                                                  "IT" => "Italy",
                                                                  "JM" => "Jamaica",
                                                                  "JP" => "Japan",
                                                                  "JO" => "Jordan",
                                                                  "KZ" => "Kazakhstan",
                                                                  "KE" => "Kenya",
                                                                  "KI" => "Kiribati",
                                                                  "KP" => "Korea, Democratic People's Republic Of",
                                                                  "KR" => "Korea, Republic Of",
                                                                  "KW" => "Kuwait",
                                                                  "KG" => "Kyrgyzstan",
                                                                  "LA" => "Lao People's Democratic Republic",
                                                                  "LV" => "Latvia",
                                                                  "LB" => "Lebanon",
                                                                  "LS" => "Lesotho",
                                                                  "LR" => "Liberia",
                                                                  "LY" => "Libyan Arab Jamahiriya",
                                                                  "LI" => "Liechtenstein",
                                                                  "LT" => "Lithuania",
                                                                  "LU" => "Luxembourg",
                                                                  "MO" => "Macau",
                                                                  "MK" => "Macedonia, Former Yugoslav Republic Of",
                                                                  "MG" => "Madagascar",
                                                                  "MW" => "Malawi",
                                                                  "MY" => "Malaysia",
                                                                  "MV" => "Maldives",
                                                                  "ML" => "Mali",
                                                                  "MT" => "Malta",
                                                                  "MH" => "Marshall Islands",
                                                                  "MQ" => "Martinique",
                                                                  "MR" => "Mauritania",
                                                                  "MU" => "Mauritius",
                                                                  "YT" => "Mayotte",
                                                                  "MX" => "Mexico",
                                                                  "FM" => "Micronesia, Federated States Of",
                                                                  "MD" => "Moldova, Republic Of",
                                                                  "MC" => "Monaco",
                                                                  "MN" => "Mongolia",
                                                                  "MS" => "Montserrat",
                                                                  "MA" => "Morocco",
                                                                  "MZ" => "Mozambique",
                                                                  "MM" => "Myanmar",
                                                                  "NA" => "Namibia",
                                                                  "NR" => "Nauru",
                                                                  "NP" => "Nepal",
                                                                  "NL" => "Netherlands",
                                                                  "AN" => "Netherlands Antilles",
                                                                  "NC" => "New Caledonia",
                                                                  "NZ" => "New Zealand",
                                                                  "NI" => "Nicaragua",
                                                                  "NE" => "Niger",
                                                                  "NG" => "Nigeria",
                                                                  "NU" => "Niue",
                                                                  "NF" => "Norfolk Island",
                                                                  "MP" => "Northern Mariana Islands",
                                                                  "NO" => "Norway",
                                                                  "OM" => "Oman",
                                                                  "PK" => "Pakistan",
                                                                  "PW" => "Palau",
                                                                  "PA" => "Panama",
                                                                  "PG" => "Papua New Guinea",
                                                                  "PY" => "Paraguay",
                                                                  "PE" => "Peru",
                                                                  "PH" => "Philippines",
                                                                  "PN" => "Pitcairn",
                                                                  "PL" => "Poland",
                                                                  "PT" => "Portugal",
                                                                  "PR" => "Puerto Rico",
                                                                  "QA" => "Qatar",
                                                                  "RE" => "Reunion",
                                                                  "RO" => "Romania",
                                                                  "RU" => "Russian Federation",
                                                                  "RW" => "Rwanda",
                                                                  "KN" => "Saint Kitts And Nevis",
                                                                  "LC" => "Saint Lucia",
                                                                  "VC" => "Saint Vincent And The Grenadines",
                                                                  "WS" => "Samoa",
                                                                  "SM" => "San Marino",
                                                                  "ST" => "Sao Tome And Principe",
                                                                  "SA" => "Saudi Arabia",
                                                                  "SN" => "Senegal",
                                                                  "SC" => "Seychelles",
                                                                  "SL" => "Sierra Leone",
                                                                  "SG" => "Singapore",
                                                                  "SK" => "Slovakia (Slovak Republic)",
                                                                  "SI" => "Slovenia",
                                                                  "SB" => "Solomon Islands",
                                                                  "SO" => "Somalia",
                                                                  "ZA" => "South Africa",
                                                                  "GS" => "South Georgia, South Sandwich Islands",
                                                                  "ES" => "Spain",
                                                                  "LK" => "Sri Lanka",
                                                                  "SH" => "St. Helena",
                                                                  "PM" => "St. Pierre And Miquelon",
                                                                  "SD" => "Sudan",
                                                                  "SR" => "Suriname",
                                                                  "SJ" => "Svalbard And Jan Mayen Islands",
                                                                  "SZ" => "Swaziland",
                                                                  "SE" => "Sweden",
                                                                  "CH" => "Switzerland",
                                                                  "SY" => "Syrian Arab Republic",
                                                                  "TW" => "Taiwan",
                                                                  "TJ" => "Tajikistan",
                                                                  "TZ" => "Tanzania, United Republic Of",
                                                                  "TH" => "Thailand",
                                                                  "TG" => "Togo",
                                                                  "TK" => "Tokelau",
                                                                  "TO" => "Tonga",
                                                                  "TT" => "Trinidad And Tobago",
                                                                  "TN" => "Tunisia",
                                                                  "TR" => "Turkey",
                                                                  "TM" => "Turkmenistan",
                                                                  "TC" => "Turks And Caicos Islands",
                                                                  "TV" => "Tuvalu",
                                                                  "UG" => "Uganda",
                                                                  "UA" => "Ukraine",
                                                                  "AE" => "United Arab Emirates",
                                                                  "GB" => "United Kingdom",
                                                                  "US" => "United States",
                                                                  "UM" => "United States Minor Outlying Islands",
                                                                  "UY" => "Uruguay",
                                                                  "UZ" => "Uzbekistan",
                                                                  "VU" => "Vanuatu",
                                                                  "VE" => "Venezuela",
                                                                  "VN" => "Viet Nam",
                                                                  "VG" => "Virgin Islands (British)",
                                                                  "VI" => "Virgin Islands (U.S.)",
                                                                  "WF" => "Wallis And Futuna Islands",
                                                                  "EH" => "Western Sahara",
                                                                  "YE" => "Yemen",
                                                                  "YU" => "Yugoslavia",
                                                                  "ZM" => "Zambia",
                                                                  "ZW" => "Zimbabwe"
                        ),
        'category' => array('1' => 'Full-Timer', '2' => 'Part-Timer'),
        'cessationCode' => array('1' => 'Resigned', '2' => 'Terminated'),
        'contractMode' => array('1' => 'Active', '2' => 'Full Terminated','3' => 'Partial Terminated','4' => 'Replacement'),
        'commissionCutoff' => array('1' => 'Last month'/*, '2' => '1 to 30 this month', '3' => '15 to 14', '4' => '26 to 25'*/),
        'creditTerm' => array('1' => 'Upon Receipt (Cash)','2' => '30 Days','3' => '60 Days','4' => '90 Days','5' => '120 Days'),
        'lead_category' => array('1' => 'Newspaper','2' => 'Referral','3' => 'Walk-In','4' => 'Website','5' => 'Bestmaid','6' => 'Netmaid','7' => 'Street Directory','8' => 'Others')
);
?>